(part "DRV134PA"
    (packageRef "DIP794W53P254L959H508Q8N")
    (interface
        (port "1" (symbPinId 1) (portName "-VO") (portType INOUT))
        (port "2" (symbPinId 2) (portName "–SENSE") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V_IN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "V-") (portType INOUT))
        (port "6" (symbPinId 6) (portName "V+") (portType INOUT))
        (port "7" (symbPinId 7) (portName "+SENSE") (portType INOUT))
        (port "8" (symbPinId 8) (portName "+VO") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "DRV134PA")
    (property "Mouser_Part_Number" "595-DRV134PA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/DRV134PA?qs=VBduBm9rCJQB2pI5Sv36eQ%3D%3D")
    (property "Arrow_Part_Number" "DRV134PA")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/drv134pa/texas-instruments.html?utm_currency=USD&region=nac")
    (property "Description" "DRV134PA, Audio Amplifier 46dB +85 C 8-Pin PDIP")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/drv134.pdf")
    (property "symbolName1" "DRV134PA")
)
