(part "OPA1641AID"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "NC_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "–IN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V–") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "V+") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "OPA1641AID")
    (property "Mouser_Part_Number" "595-OPA1641AID")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/OPA1641AID?qs=%2Fqzd9s%252BcLd4V%252BdtTTJDooA%3D%3D")
    (property "Arrow_Part_Number" "OPA1641AID")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/opa1641aid/texas-instruments.html?utm_currency=USD&region=europe")
    (property "Description" "Single Sound-Plus High-Performance, JFET-Input Audio OpAmps")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/opa1641")
    (property "symbolName1" "OPA1641AID")
)
