(part "OPA1644AID"
    (packageRef "SOIC127P600X175-14N")
    (interface
        (port "1" (symbPinId 1) (portName "OUT_A") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-IN_A") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+_IN_A") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V+") (portType INOUT))
        (port "5" (symbPinId 5) (portName "+IN_B") (portType INOUT))
        (port "6" (symbPinId 6) (portName "-_IN_B") (portType INOUT))
        (port "7" (symbPinId 7) (portName "OUT_B") (portType INOUT))
        (port "8" (symbPinId 8) (portName "OUT_C") (portType INOUT))
        (port "9" (symbPinId 9) (portName "-IN_C") (portType INOUT))
        (port "10" (symbPinId 10) (portName "+_IN_C") (portType INOUT))
        (port "11" (symbPinId 11) (portName "V-") (portType INOUT))
        (port "12" (symbPinId 12) (portName "+IN_D") (portType INOUT))
        (port "13" (symbPinId 13) (portName "-_IN_D") (portType INOUT))
        (port "14" (symbPinId 14) (portName "OUT_D") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "OPA1644AID")
    (property "Mouser_Part_Number" "595-OPA1644AID")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/OPA1644AID?qs=%2Fqzd9s%252BcLd4i%2FOCXbst%2F%252Bw%3D%3D")
    (property "Arrow_Part_Number" "OPA1644AID")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/opa1644aid/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "OPA1641/1642/1644 SoundPLUS High-Performance, JFET-Input Audio OpAmps")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/opa1644")
    (property "symbolName1" "OPA1644AID")
)
