(part "INA137PA"
    (packageRef "DIP794W53P254L959H508Q8N")
    (interface
        (port "1" (symbPinId 1) (portName "REF") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-IN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V-") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SENSE") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUTPUT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "V+") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "INA137PA")
    (property "Mouser_Part_Number" "595-INA137PA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/INA137PA?qs=VBduBm9rCJR0Awr2sjGHZA%3D%3D")
    (property "Arrow_Part_Number" "INA137PA")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ina137pa/texas-instruments?region=nac")
    (property "Description" "Audio Differential Line Receivers, +-6dB (G=1/2 or 2)")
    (property "Datasheet_Link" "https://www.ti.com/lit/gpn/ina137")
    (property "symbolName1" "INA137PA")
)
